name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ShortcutService/ShortcutService.csproj

      - name: Build
        run: dotnet build ShortcutService/ShortcutService.csproj --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test ShortcutService.Tests/ShortcutService.Tests.csproj --no-build --verbosity normal

      - name: Run integration tests
        run: dotnet test ShortcutService.IntegrationTests/ShortcutService.IntegrationTests.csproj --no-build --verbosity normal
